#ifndef KBD_LAYOUT_H
#define KBD_LAYOUT_H

#include "ast_keys.h"

#define PKEY_NONE		STKEY_NONE

/* keys layout */
#define PKEY_ESC		STKEY_ESC

#define PKEY_F1			STKEY_F1
#define PKEY_F2			STKEY_F2
#define PKEY_F3			STKEY_F3
#define PKEY_F4			STKEY_F4
#define PKEY_F5			STKEY_F5
#define PKEY_F6			STKEY_F6
#define PKEY_F7			STKEY_F7
#define PKEY_F8			STKEY_F8
#define PKEY_F9			STKEY_F9
#define PKEY_F10		STKEY_F10
#define PKEY_F11		STKEY_HELP
#define PKEY_F12		STKEY_UNDO

#define PKEY_TILDE		STKEY_TILDE
#define PKEY_1			STKEY_1
#define PKEY_2			STKEY_2
#define PKEY_3			STKEY_3
#define PKEY_4			STKEY_4
#define PKEY_5			STKEY_5
#define PKEY_6			STKEY_6
#define PKEY_7			STKEY_7
#define PKEY_8			STKEY_8
#define PKEY_9			STKEY_9
#define PKEY_0			STKEY_0
#define PKEY_MINUS		STKEY_MINUS
#define PKEY_EQUAL		STKEY_EQUAL
#define PKEY_BACKSLASH	STKEY_BACKSLASH
#define PKEY_BACKSPACE	STKEY_BACKSPACE

#define PKEY_TAB		STKEY_TAB
#define PKEY_Q			STKEY_Q
#define PKEY_W			STKEY_W
#define PKEY_E			STKEY_E
#define PKEY_R			STKEY_R
#define PKEY_T			STKEY_T
#define PKEY_Y			STKEY_Y
#define PKEY_U			STKEY_U
#define PKEY_I			STKEY_I
#define PKEY_O			STKEY_O
#define PKEY_P			STKEY_P
#define PKEY_LBRACE		STKEY_LBRACE
#define PKEY_RBRACE		STKEY_RBRACE

#define PKEY_CAPSLOCK	STKEY_CAPSLOCK
#define PKEY_A			STKEY_A
#define PKEY_S			STKEY_S
#define PKEY_D			STKEY_D
#define PKEY_F			STKEY_F
#define PKEY_G			STKEY_G
#define PKEY_H			STKEY_H
#define PKEY_J			STKEY_J
#define PKEY_K			STKEY_K
#define PKEY_L			STKEY_L
#define PKEY_SEMICOLON	STKEY_SEMICOLON
#define PKEY_QUOTE		STKEY_QUOTE
#define PKEY_RETURN		STKEY_RETURN

#define PKEY_LSHIFT		STKEY_LSHIFT
#define PKEY_Z			STKEY_Z
#define PKEY_X			STKEY_X
#define PKEY_C			STKEY_C
#define PKEY_V			STKEY_V
#define PKEY_B			STKEY_B
#define PKEY_N			STKEY_N
#define PKEY_M			STKEY_M
#define PKEY_COMMA		STKEY_COMMA
#define PKEY_PERIOD		STKEY_PERIOD
#define PKEY_SLASH		STKEY_SLASH
#define PKEY_RSHIFT		STKEY_RSHIFT

#define PKEY_LCTRL		STKEY_CTRL
#define PKEY_LWIN		STKEY_NONE
#define PKEY_LALT		STKEY_ALT
#define PKEY_SPACE		STKEY_SPACE
#define PKEY_RALT		STKEY_ALT
#define PKEY_RWIN		STKEY_NONE
#define PKEY_MENU		STKEY_NONE
#define PKEY_RCTRL		STKEY_CTRL

#define PKEY_PRTSRC		STKEY_NONE
#define PKEY_SCRLOCK	STKEY_NONE
#define PKEY_INSERT		STKEY_INSERT
#define PKEY_DELETE		STKEY_DELETE
#define PKEY_HOME		STKEY_HOME
#define PKEY_END		STKEY_NONE
#define PKEY_PAGEUP		STKEY_KP_LBR
#define PKEY_PAGEDOWN	STKEY_KP_RBR

#define PKEY_UP			STKEY_UP
#define PKEY_DOWN		STKEY_DOWN
#define PKEY_LEFT		STKEY_LEFT
#define PKEY_RIGHT		STKEY_RIGHT

#define PKEY_NUMLOCK	STKEY_NONE
#define PKEY_KP_0		STKEY_KP_0
#define PKEY_KP_1		STKEY_KP_1
#define PKEY_KP_2		STKEY_KP_2
#define PKEY_KP_3		STKEY_KP_3
#define PKEY_KP_4		STKEY_KP_4
#define PKEY_KP_5		STKEY_KP_5
#define PKEY_KP_6		STKEY_KP_6
#define PKEY_KP_7		STKEY_KP_7
#define PKEY_KP_8		STKEY_KP_8
#define PKEY_KP_9		STKEY_KP_9
#define PKEY_KP_PERIOD	STKEY_KP_PERIOD
#define PKEY_KP_DIV		STKEY_KP_DIV
#define PKEY_KP_MUL		STKEY_KP_MUL
#define PKEY_KP_MINUS	STKEY_KP_MINUS
#define PKEY_KP_PLUS	STKEY_KP_PLUS
#define PKEY_KP_ENTER	STKEY_KP_ENTER

#endif
